########################################################################################
#                                                                                      #
#      WAVIN AHC-9000 FLOOR HEATING CONTROLLER SOFTWARE FOR HOME ASSISTANT             #
#                                                                                      #   
#        Code developed by : Heine Koldbro Madsen and Samuel Sieb 2021                 #
#                                                                                      #
#           https://github.com/heinekmadsen/esphome_wavinahc9000v3/tree/main           #    
#                                                                                      #
# Hardware by : Mogens Groth Nicolaisen https://github.com/nic6911/Wavin-AHC-9000-mqtt #
#                                                                                      #
########################################################################################
 
esphome:
  name: wavin
  friendly_name: Wavin

esp8266:
  board: esp01_1m
  framework:
    type: esp-idf

external_components:
  - source: github://nic6911/esphome_wavinahc9000v3@simplifications
    components: [wavin_ahc9000]
    refresh: 0s

logger:
  baud_rate: 0

uart:
  id: uart_wavin
  tx_pin: TX
  rx_pin: RX
  baud_rate: 38400
  stop_bits: 1
  parity: NONE

wavin_ahc9000:
  id: wavin
  uart_id: uart_wavin
  update_interval: 10s
  allow_mode_writes: false
  poll_channels_per_cycle: 1
  tx_enable_pin: 2

  channel_01_friendly_name: "Bryggers"
  channel_02_friendly_name: "Lille badeværelse"
  channel_03_friendly_name: "Kontor"
  channel_04_friendly_name: "Gæsteværelse"
  channel_05_friendly_name: "Lyahs værelse"
  channel_06_friendly_name: "Soveværelse"
  channel_07_friendly_name: "Badeværelse"
  channel_08_friendly_name: "Stue"
  channel_09_friendly_name: "Køkken"
  channel_10_friendly_name: "Gang"

climate:
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Bryggers"
    channel: 1
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Lille badeværelse"
    channel: 2
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Kontor"
    channel: 3
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Gæsteværelse"
    channel: 4
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Lyahs værelse"
    channel: 5
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Soveværelse"
    channel: 6
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Badeværelse"
    channel: 7
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Stue"
    channel: 8
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Køkken"
    channel: 9
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Gang"
    channel: 10

sensor:
  # Ch.1 Bryggers
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Bryggers Batteri"
    channel: 1
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Bryggers Temperatur"
    channel: 1
    type: temperature

  # Ch.2 Lille badeværelse
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Lille badeværelse Batteri"
    channel: 2
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Lille badeværelse Temperatur"
    channel: 2
    type: temperature

  # Ch.3 Kontor
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Kontor Batteri"
    channel: 3
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Kontor Temperatur"
    channel: 3
    type: temperature

  # Ch.4 Gæsteværelse
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Gæsteværelse Batteri"
    channel: 4
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Gæsteværelse Temperatur"
    channel: 4
    type: temperature

  # Ch.5 Lyahs værelse
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Lyahs værelse Batteri"
    channel: 5
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Lyahs værelse Temperatur"
    channel: 5
    type: temperature

  # Ch.6 Soveværelse
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Soveværelse Batteri"
    channel: 6
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Soveværelse Temperatur"
    channel: 6
    type: temperature

  # Ch.7 Badeværelse
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Badeværelse Batteri"
    channel: 7
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Badeværelse Temperatur"
    channel: 7
    type: temperature

  # Ch.8 Stue
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Stue Batteri"
    channel: 8
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Stue Temperatur"
    channel: 8
    type: temperature

  # Ch.9 Køkken
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Køkken Batteri"
    channel: 9
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Køkken Temperatur"
    channel: 9
    type: temperature

  # Ch.10 Gang
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Gang Batteri"
    channel: 10
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Gang Temperatur"
    channel: 10
    type: temperature

api:

wifi:
  networks:
    #hidden: true
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    
    manual_ip:
      static_ip: 192.168.20.10
      gateway: 192.168.20.1
      subnet: 255.255.255.0
      dns1: 192.168.20.1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wavin Fallback Hotspot"
    password: "fallback123"

captive_portal:  

ota:
  - platform: esphome
    password: "945ac67ddcae11048f6a488672b6aadb"
    #password: !secret esphome_ota_password
